feat(01-building-blocks): added worrkflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,21 +1,23 @@
-name: 01 - Building Blocks
+name: 01-Building Blocks
 
 on: push
-
-jobs:    
+    
+jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-        - name: Say hello
-          run: echo "Hello, world!"
+      - name: Say hello
+        run: echo "Hello, world!"
+
   echo-goodbye:
-          runs-on: ubuntu-latest
+    runs-on: ubuntu-latest
     steps:
-        - name: Failed step
-          run:
-            echo "I will fail"
-            exit 1
-        - name: Say goodbye
-          run: echo "Goodbye!" 
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+      
+      - name: Say goodbye
+        run: echo "Goodbye!"
 
 
